apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-msg-broker-deployment
  namespace: app-msg-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-msg-broker
  template:
    metadata:
      labels:
        app: app-msg-broker
    spec:
      containers:
      - name: app-msg-broker
        image: app-msg-broker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
