apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-msg-broker-get-pods
  namespace: app-msg-broker
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-msg-broker-get-pods
  namespace: app-msg-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-msg-broker-get-pods
subjects:
- kind: ServiceAccount
  name: default
  namespace: app-msg-broker
